Create aha-vascular including unique footer
parameter1/ascend-media-newsletters pull request #10
Opened 2021-08-16 14:56 UTC by jwade1327

<img width="655" alt="Screen Shot 2021-08-16 at 9 55 03 AM" src="https://user-images.githubusercontent.com/64623209/129584158-500e1474-af8b-4aa1-9ea9-f5d9819573b6.png">

2021-08-16 15:30 UTC, brandonbk requested changes

2021-08-16 15:30 UTC, brandonbk commented on packages/common/components/blocks/footer-aha.marko
> +              <td align="left" valign="top" style=standardStyle>
@jwade1327 - for each of these anchor tags, add `style=standardUnderlineStyle` to be consistent with the unsubscribe link above.  This should change the blue links to white.

2021-08-16 15:37 UTC, jwade1327 commented
<img width="615" alt="Screen Shot 2021-08-16 at 10 36 01 AM" src="https://user-images.githubusercontent.com/64623209/129590145-43e427c2-0a2e-45fa-b332-d10336fe1ca4.png">

2021-08-16 15:37 UTC, jwade1327 commented on packages/common/components/blocks/footer-aha.marko
> +              <td align="left" valign="top" style=standardStyle>
@brandonbk the link styling has been updated

2021-08-17 13:49 UTC, brandonbk approved these changes

2021-08-17 13:49 UTC, merged