Add 'advertise' to Bulletin footer
parameter1/ascend-media-newsletters pull request #121
Opened 2023-01-13 02:29 UTC by jwade1327

<img width="744" alt="Screen Shot 2023-01-12 at 8 28 02 PM" src="https://user-images.githubusercontent.com/64623209/212223300-78033bce-7ee7-4c49-9527-66e1e9c2ee97.png">

2023-01-13 02:30 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Bulletin: Add to footer](https://trello.com/c/grPOcsHF/414-bulletin-add-to-footer)

2023-01-13 20:55 UTC, Shinsina requested changes

2023-01-13 20:55 UTC, Shinsina commented on packages/common/components/blocks/footer.marko
>              <if(copyright)>
Ref: https://markojs.com/docs/syntax/#dynamic-text just pass this entire thing in and render it as HTML instead of creating multiple variables and having to make a code change to change the hardcoded portion if this gets used again in the future by someone else

2023-01-16 17:44 UTC, jwade1327 commented on packages/common/components/blocks/footer.marko
> +$ const advertiseCont = get(newsletterConfig, "footer.advertiseCont");
@Shinsina Forgot to delete that! Thanks!

2023-01-16 17:54 UTC, Shinsina approved these changes

2023-01-16 17:54 UTC, merged