Increase limits AAD 1-3 and create AAD-4
parameter1/ascend-media-newsletters pull request #133
Opened 2023-02-27 14:57 UTC by jwade1327

![screencapture-localhost-22290-templates-aad-enewsletter-1-2023-02-27-08_17_21](https://user-images.githubusercontent.com/64623209/221597879-7282b809-a725-4a12-9c41-31134e191e0f.png)
![screencapture-localhost-22290-templates-aad-enewsletter-4-expanded-2023-02-27-08_53_29](https://user-images.githubusercontent.com/64623209/221597906-b1bf0cc1-caf3-41e5-92b2-b4224c4ba820.png)

2023-02-27 14:58 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [New AAD eNewsletter Template](https://trello.com/c/unb1tOAx/437-new-aad-enewsletter-template)

2023-02-27 14:58 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [AAD Newsletter Template Update](https://trello.com/c/yHys5rok/438-aad-newsletter-template-update)

2023-02-27 21:26 UTC, Shinsina requested changes

2023-02-27 21:26 UTC, Shinsina commented on tenants/all/templates/aad-enewsletter-3.marko
> +
Noticed that `tenants/all/template/aad-newsletter-4-expanded.marko` only has 13 ad slots and doesn't seem to line up with the rest of these adjustments is this intentional?

2023-02-27 21:26 UTC, Shinsina commented on tenants/all/templates/aad-enewsletter-4-expanded.marko
> +        />
I'm confused are these link-label-props still being used by anything and if they are, are these both supposed to be 15 or is this a mistake?

2023-02-28 03:42 UTC, jwade1327 commented on tenants/all/templates/aad-enewsletter-4-expanded.marko
> +        />
@Shinsina Fixed.

2023-03-01 18:33 UTC, Shinsina approved these changes

2023-03-01 18:33 UTC, merged