Create AUA Daily Expanded
parameter1/ascend-media-newsletters pull request #142
Opened 2023-04-04 20:29 UTC by jwade1327

![screencapture-localhost-22290-templates-aua-daily-expanded-2023-04-04-15_27_54](https://user-images.githubusercontent.com/64623209/229913033-7ed9838c-e054-4386-994b-267fa108d2f1.png)

2023-04-04 20:30 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [AUA New Email Template](https://trello.com/c/MsIYBv5B/456-aua-new-email-template)

2023-04-05 15:06 UTC, Shinsina requested changes

2023-04-05 15:06 UTC, Shinsina commented on tenants/all/templates/aua-daily-expanded.marko
> +        <!--Ad Slot 10 -->
I've seen Ad Slot 10 4 times now, these should be corrected even if they're simply copy pasted, also there should be a space prior to `Ad` (not sure how many of these comments this impacts but I noticed it on this one in particular after seeing it 4 times :)

2023-04-05 15:10 UTC, Shinsina approved these changes

2023-04-05 15:11 UTC, merged