Update amPulmonary footer info
parameter1/ascend-media-newsletters pull request #171
Opened 2024-03-15 18:50 UTC by jwade1327

<img width="670" alt="Screenshot 2024-03-15 at 1 49 58 PM" src="https://github.com/parameter1/ascend-media-newsletters/assets/64623209/d613dbd7-bcc5-4d0b-a381-97054db77eee">

2024-03-15 18:50 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [amPulmonary eNewsletter template](https://trello.com/c/o6zcgp5h/551-ampulmonary-enewsletter-template)

2024-08-05 20:11 UTC, Shinsina requested changes
I believe the zip change made

2024-08-05 20:11 UTC, Shinsina commented on tenants/all/config/core.js
> +      address: '1650 Diagonal Rd<br/>Alexandria, VA 64081',
I believe this is being wrongly changed, I believe the Zip that needs to be changed is found in either `am-footer.marko` (already changed in this PR) or `brands.js` where it is stored as `ascendAddress`

2024-08-06 14:45 UTC, Shinsina approved these changes

2024-08-06 14:45 UTC, merged