Update hypertension newsletter with header image & change to footer
parameter1/ascend-media-newsletters pull request #22
Opened 2021-08-30 13:41 UTC by jwade1327

<img width="652" alt="Screen Shot 2021-08-30 at 8 39 52 AM" src="https://user-images.githubusercontent.com/64623209/131348538-f680a9c2-a855-4ccd-a8bc-5ba1ab07033f.png">

2021-08-30 13:44 UTC, jwade1327 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Phase 1: AHA - Hypertension eNewsletter Initial Setup](https://trello.com/c/gN9fu4CT/165-phase-1-aha-hypertension-enewsletter-initial-setup)

2021-08-30 14:44 UTC, jwade1327 commented
<img width="644" alt="Screen Shot 2021-08-30 at 9 43 19 AM" src="https://user-images.githubusercontent.com/64623209/131357678-6a54301c-dc11-4f4a-89a0-32cdb066ae3a.png">

2021-08-31 13:19 UTC, B77Mills requested changes

2021-08-31 13:19 UTC, B77Mills commented on packages/common/components/blocks/footer-aha.marko
> +              <td align="right" valign="top" style=brandStyle>
@jwade1327  This should be wrapped in a <tr></tr>

2021-08-31 13:28 UTC, jwade1327 commented on packages/common/components/blocks/footer-aha.marko
> +              <td align="right" valign="top" style=brandStyle>
@B77Mills change has been made!

2021-08-31 14:02 UTC, merged